import React, {useState, useEffect} from 'react'
import { Router, useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import SetList from '../components/setList'

export default function Home({ workoutData, routineData }) {
  const router = useRouter();

  const refreshData = () => {
    router.replace(router.asPath);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SetList movements={workoutData} />

      </main>
    </div>
  )
}

export async function getStaticProps() {
  const workoutDataRes = await fetch(`http://localhost:3333/movements/5`, {accept: "application/json"});
  const workoutData = await workoutDataRes.json();
  
  const routineDataRes = await fetch(`http://localhost:3333/routines`, {accept: "application/json"});
  const routineData = await routineDataRes.json();

  return { props: { workoutData, routineData } }
}
