import React, {useState, useEffect} from 'react'
import { Router, useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.scss'
import SetList from '../components/setList'
import Navigation from '../components/Navigation'

export default function Home({ workoutData, routineData, today, thisRoutine, nextRoutine }) {
  const router = useRouter();
  const databaseUrl = `http://localhost:3333`;

  const refreshData = () => {
    router.replace(router.asPath);
  }

  return (
    <div>
      <Head>
        <title>Workout tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation thisRoutine={thisRoutine}
          nextRoutine={nextRoutine}
          routines={routineData}
          databaseUrl={databaseUrl} />
        <SetList movements={workoutData}
          today={today}
          routineId={thisRoutine.routine_id}
          databaseUrl={databaseUrl} />
      </main>
    </div>
  )
}

// export async function getServerSideProps() {
//   const routineId = params.routineId;
//   apiUrl = process.env.apiUrl || `http://localhost:3333`;
// }

export async function getStaticProps() {
  const apiUrl = process.env.API_URL || `http://localhost:3333`;
  let routineData,
      workoutData,
      thisRoutine,
      nextRoutine,
      today;

  await fetch (`${apiUrl}/routine/current`, { accept: "application/json" })
  .then (data => data.json())
  .then (data => {
    routineData = data.routines;
    workoutData = data.movements;
    thisRoutine = data.thisRoutine;
    nextRoutine = data.nextRoutine;
    today = data.todaysDate;
  })

  return { props: { workoutData, routineData, thisRoutine, nextRoutine, today } }
}
